# Generated by Django 5.2.14 on 2026-05-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
